### ISSUE TITLE
Maven Plugin - Add support for recordTestResults

### ISSUE THREAD

**Issue by anjo-swe** [openclover/clover#123]
Trying to follow https://confluence.atlassian.com/clover/unit-test-results-and-per-test-coverage-71600263.html but it’s unclear on how to do that when using the maven plugin

**Ant**
* https://confluence.atlassian.com/clover/clover-setup-71600085.html
* Parameter: `recordTestResults`

**Maven**
* http://openclover.org/doc/maven/4.4.1/setup-mojo.html
* Add support for `recordTestResults` when using `mvn clean clover:setup verify clover:aggregate`
  * e.g. User property: `maven.clover.recordTestResults`

Related legacy tickets: 
* https://bitbucket.org/openclover/clover/issues/29/junit-rule-expectedexception-marked-as
* https://jira.atlassian.com/browse/CLOV-1063

**Comment by marek-parfianowicz** [comment]
PR: https://github.com/openclover/clover-maven-plugin/pull/45
