### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by ccostin93** [openclover/clover#191]
When will be the next release of the project?
I am interested in this issue https://github.com/openclover/clover/issues/20 which seems to already be fixed, but not released.

**Comment by marek-parfianowicz** [comment]
Hi Constantin! 

It's hard for me to give an exact release date. If you look at the current 4.5.0 roadmap (https://github.com/openclover/clover/milestone/11) you'll see it's 89% complete. The largest in-progress feature, issue #116 "Migrate build system from Ant to Maven" has 17 out of 18 tasks completed. The remaining work is: testing the build and release process to ensure there are no side-effects or bugs as a result of the Maven migration; plus using a Proguard to reduce size of binaries. 

I estimate I need 3 full working days to complete the testing and 1-2 days for the release itself. I hope to find free time to do it in the next 3 months. I hope this helps.

Cheers
Marek

**Comment by RadixSeven** [comment]
First, thank you for working on this. Clover is much better for my team than any of its alternatives. Though I've talked to my superiors about using work time to contribute, they felt that other matters were more important in our current situation; I've made a similar decision about my non-work life. So, anything we get out of this is more than we've put in - and whatever time you choose to put into the project is laudable. I do not mean to suggest you have any obligation by talking about the timelines below.

*Events that will impact Clover's future usage in the absence of regular updates*
* [RedHat support for OpenJDK 11 ends in October 2024](https://access.redhat.com/articles/1299013). At that point, we will migrate to Java 17 or 19. I expect everything to be fine for this upgrade, but language changes will eventually drift outside of the code Clover's parser understands without future maintenance.
* A security flaw affects one of Clover's dependencies (I forget which). The current version patches the vulnerability. To continue using Clover, my team built our own jar. (Our client will not allow us to release it publicly for fear of potential liability.) I got our clients to agree to that work by telling them that Clover would have an official version with the patch we needed by January. I won't be able to repeat that, so if we get another flaw that persists longer than the time window their policy allows for closing holes, they may force us to abandon Clover for a more widely-used tool. (This is not faulting you, I'm just sharing the kind of decisions that I expect to be common in the userbase.)

**Comment by marek-parfianowicz** [comment]
> First, thank you for working on this. Clover is much better for my team than any of its alternatives.

I'm really happy to hear this :) 

> Though I've talked to my superiors about using work time to contribute, they felt that other matters were more important.

I understand. I think this is a problem of many open source projects. Many users but not so many contributors... Based on number of downloads from the website, or Jenkins instances reporting the Clover plugin, I estimate that at least 50'000 developers are using OpenClover. Yet, number of external contributors can be counted on one hand (sic!).

> language changes will eventually drift outside of the code Clover's parser understands without future maintenance.

Thanks to one amazing contribution last year, Clover 4.5.0 should be ready to handle Java 17 syntax (yay!). It will be announced as beta, as I didn't have a chance to run extensive syntax testing. Also, automatic instrumentation of module-info.java files is not implemented yet.

> A security flaw affects one of Clover's dependencies (I forget which). 

I think you refer to Log4j 1.2 https://github.com/openclover/clover/issues/165. Migrated to SLF4J. Although the real risk was pretty low, it was only a supplementary logger, mainly for debugging.

**Comment by RadixSeven** [comment]
>  Clover 4.5.0 should be ready to handle Java 17 syntax (yay!).
That is really good news. We have several thousand lines of code (`cloc` says 5538) that I hope we'll be able to remove with the new syntax. (In particular, the current parser fails with type annotations inside generics, so we have a parallel container hierarchy that manually adds our type annotations to method signatures.)

**Comment by marek-parfianowicz** [comment]
Hey everyone, I have great news. 

The largest branch OC-116-migrate-ant-to-maven (over 170 commits, been in development for one year) has been merged to master. I'm working on OC-112 guava removal and some minor library updates reported by Dependabot (all should be merged today). 

I'm after manual exploratory testing of all OpenClover plugins and the CI is green too (although with some re-runs, due to a few unstable Groovy and IDEA tests).

So the only things remaining are: to test the release process with Maven, write some release documentation for openclover.org website, reach out to Atlassian Bamboo team to test the release candidate (Bamboo bundles both Atlassian Clover and OpenClover). 

ETA for the 4.5.0 release is week 18-22 September.

**Comment by marek-parfianowicz** [comment]
Feel free to download org.openclover:clover artifact using the link above and test it. Please report any issues in the comments.

**Comment by marek-parfianowicz** [comment]
Hi! I have released OpenClover 4.5.0 last week, see the http://openclover.org/doc/openclover-4.5.0-release-notes.html for details.

**Comment by RadixSeven** [comment]
Thank you for all your hard work. I made a ticket to upgrade as soon as our product owner lets us.
