### ISSUE TITLE
The link for Eclipse plugin returns 404

### ISSUE THREAD

**Issue by satob** [openclover/clover#211]
On https://openclover.org/downloads , the link for OpenClover 4.5.0 Eclipse plugin returns a 404 error.

Instructions to install OpenClover to Eclipse (https://openclover.org/doc/manual/latest/eclipse--openclover-for-eclipse-in-10-minutes.html) works properly.

**Comment by marek-parfianowicz** [comment]
Fixed. Thanks for spotting this! Just keep in mind that a really old Eclipse is required to run this plugin. Cheers!

**Comment by satob** [comment]
> Fixed. Thanks for spotting this! Just keep in mind that a really old Eclipse is required to run this plugin. Cheers!

Thank you for fixing the problem. Then, does it mean that you cannot this Eclipse plugin doesn't work properly in recent versions of Eclipse?

If so, is there any recommended way to use OpenClover with recent versions of Eclipse?

**Comment by marek-parfianowicz** [comment]
I'm afraid there isn't. I focus mainly on build tools (ant, maven) and java language.
