### ISSUE TITLE
Support Java14 instanceof pattern matching

### ISSUE THREAD

**Issue by marek-parfianowicz** [openclover/clover#214]
Java 14 introduced pattern matching for `instanceof` keyword, which allows to create a variable for the type matched, without type casting. Example:

`int sum = 0;
if (o instanceof Integer i) {
    sum += i;
}
`

To be implemented: optional identifier after type declaration.

**Comment by Haixing-Hu** [comment]
Hi, the following code will cause an error at 4.5.2 
```
int sum = 0; if (o instanceof final Integer i) { sum += i; } 
```

The only different is to add a `final` keyword between `instanceof` and `Integer`.

**Comment by marek-parfianowicz** [comment]
Thank you for reporting this bug. I think it's already fixed, I see necessary declaration on the master branch:

https://github.com/openclover/clover/blob/fc5760c44ac4c6fd7a77fbe804ad26b12b231bb9/clover-core/src/main/java/org/openclover/core/instr/java/java.g#L3279

It's just not released. 



Sent from Nine
________________________________
