### ISSUE TITLE
Instrumentation of generic records fails

### ISSUE THREAD

**Issue by matic277** [openclover/clover#251]
Instrumentation of records with generic types fails.
Example:
```
public class Main
{
  record GenericRecord<T>(T type) { } // This is line 6
  public static void main(String[] args)
  {
    System.out.println();
  }
}
```
Fails with:
`ERROR: C:\.....\TestProject\src\main\java\org\example\Main.java:6:23:expecting LPAREN, found '<'`

Using Java 17 with Clover 4.5.2.

**Comment by marek-parfianowicz** [comment]
Thank you for reporting this problem. I will fix it in the upcoming release.

**Comment by marek-parfianowicz** [comment]
PR #255
