### ISSUE TITLE
Integrating Clover with JUnit 5 Parameterized Tests

### ISSUE THREAD

**Issue by marek-parfianowicz** [openclover/clover#92]
Clover is not able to display test results properly if the tests are run with new Junit Platform (Junit 5) even though the tests are using Junit 4 Parameterized Runner class.

**Comment by marek-parfianowicz** [comment]
Original report: https://bitbucket.org/openclover/clover/issues/92

**Comment by scyd** [comment]
@marek-parfianowicz is this today supported ?
Does latest clover support JUnit 5 and @ParameterizedTest ?

**Comment by marek-parfianowicz** [comment]
Yes, it's supported since version 4.4.0.

Sent from Nine
________________________________
